_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 55
                - 103
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.18.2
            "6": 4.44.2
            "8":
                - 1
                - 5
            "12": 0.18.2
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 10
learning_rate:
    value: 0.001
