pretrained_model: timm/efficientvit_m2.r224_in1k
pretrained: True
num_classes: 2
num_labels: 2
loss_weights:
  g: 0.1
  Q: 0.1
CUDA: True
learning_rate: 2e-5


#
df_path: /root/graduation_thetis/causal-bert-pytorch/input/outputs_v4.csv
image_column: img_path
confounds_column: light_or_dark
treatments_column: price_ave
outcome_column: outcome

batch_size: 2
num_workers: 32
epoch: 3

total_training_steps: ??? 